### ISSUE TITLE
Integrate web server

### ISSUE THREAD

**Issue by htfy96** [sjtug/lug#16]
- [x] Add `serve(request), canServe(request)` to `interface Worker`
- [x] Add config about web server
- [ ] Add metrics for web server
- [x] Record log for web server
- [ ] Update wiki/docs

https/auth/rate limiting will not be implemented, since finally `lug` will be deployed behind `traefik`.
```
Request --> dispatcher ---[ iterate workers, if canServe]--> worker.serve
                     \-----------------> Prometeus
```

**Comment by shanzi** [comment]
Wow.... Adding Prometheus? Sounds fun... but seems not necessary?

**Comment by htfy96** [comment]
@shanzi Prometheus support of sync worker has already been merged to master. It is an optional feature.

After discussion with @codeworm96, we finally abandoned to integrate web server into lug to persist the simplicity of this project. Reverse Proxy will be supported via external ways.
