### ISSUE TITLE
内置HTTP服务器？

### ISSUE THREAD

**Issue by htfy96** [sjtug/lug#5]
目前我的想法是不内置服务器，原因有：
- 方便替换原有体系
- tunasync内置，是因为当时缺乏一种简单、方便配置服务器的方法。现在我们有[Candy](https://github.com/mholt/caddy)，可以做到自动签发、处理证书，而且配置比tunasync更简单

**Comment by shanzi** [comment]
@htfy96 你的意思是在总的 scheduler 上内置服务器么？我觉得scheduler不应该内置服务器，但是应该开放某种接口可以使用 RPC 或者 IPC 让外界可以 inspect server 的状态

**Comment by shanzi** [comment]
@htfy96 看样子manager已经暴露了一个 json 的 api，赞一个。。。

以后也许可以考虑引入 swagger 或者 protobuf 这样的工具来做 API 这边的设计 :D
